services:
  backend:
    build: .
    container_name: isp-saas-backend

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/isp_saas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234