spring.application.name=wifi
spring.profiles.active=dev

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true 

#File Upload
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

#Automatic Billing
scheduler.enabled=false

