spring.application.name=wifi

spring.datasource.url=jdbc:postgresql://localhost:5432/isp_saas
spring.datasource.username=your_username
spring.datasource.password=your_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=yourVeryLongSecretKeyYourVeryLongSecretKey123456
jwt.expiration=3600000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_gmail@gmail.com
# your app password that is 16 characters long
spring.mail.password=abcd efgh ijkl

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true